artifact_location: file:///c:/Users/rodri/Documents/AI/FIA/model_trained/mlflow/0
creation_time: 1726233897772
experiment_id: '0'
last_update_time: 1726233897772
lifecycle_stage: active
name: Default
